# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c87ba33cd89bdca1426ac565061cf1ee71c25069624389d11b64600cd47c1c6e3544dc7cf2f53472f2b7c49929956cc746944ba2cd01dce36019eb3aab550003

test:
  secret_key_base: 6b262ad739fbe83c41111eaa6178c4f04e19b090f5dcb4957f6427bf7fc889c4597a40e25185e5a94684147107333e73e85733454e1d0d38d2e379ffb6bc79ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
